name: Helm Lint

on:
  workflow_call:
    inputs:
      path:
        description: 'Path to the Helm chart directory'
        required: true
        type: string
      runner:
        description: 'Runner label'
        required: false
        default: 'self-hosted'
        type: string

jobs:
  helm-lint:
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1

      - name: Helm lint
        run: helm lint .
