name: Helm Lint

on:
  workflow_call:
    inputs:
      path:
        description: 'Path to the Helm chart directory'
        required: true
        type: string
      runner:
        description: 'Runner label'
        required: false
        default: 'self-hosted'
        type: string

jobs:
  helm-lint:
    runs-on: ${{ inputs.runner }}
    defaults:
      run:
        working-directory: ${{ inputs.path }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0

      - name: Helm lint
        run: helm lint .
