name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: ./.github/workflows/semantic-release.yml
    secrets:
      APP_ID: ${{ secrets.RELEASE_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.RELEASE_APP_SECRET }}
